# Generated by Django 3.2.9 on 2024-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_shoppingcartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='shoppingcart_set', to='cart.ShoppingCartItem'),
        ),
    ]
