# Generated by Django 3.2.9 on 2024-07-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
