# Generated by Django 3.2.9 on 2024-07-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel'),
        ),
    ]
