# Generated by Django 3.2.9 on 2024-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_carousel_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinlandi'), ('deleted', 'Silindi')], default='draft', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
