# Generated by Django 3.2.9 on 2024-07-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20240718_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_men',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_women',
        ),
    ]
